vich_uploader:
    db_driver: orm
    storage: gaufrette

    metadata:
        type: attribute
        
    mappings:
        estate_ad:
            uri_prefix: /recipe
            upload_destination: recipe
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        uploads:
            uri_prefix: /uploads
            upload_destination: uploads
            namer: Vich\UploaderBundle\Naming\HashNamer