index: ingredient

body:
    settings: 
        number_of_shards: 3
        number_of_replicas: 2
    
    mappings: 
        _source: 
            enabled: true
        properties: 
            name: 
                type: text
            image: 
                type: text
                index: false