index: ingredient
repository: 'App\Repository\IngredientRepository'

body:
    settings: 
        number_of_shards: 3
        number_of_replicas: 0
    
    mappings: 
        _source: 
            enabled: true
        properties:
            name: 
                type: text
            